plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.6' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
	group = 'com.cc'
	version = '0.0.1-SNAPSHOT'

	repositories {
		mavenCentral()
	}
}

subprojects {
	apply plugin: 'java'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(17)
		}
	}

	configurations {
		compileOnly {
			extendsFrom annotationProcessor
		}
	}

	ext {
		springCloudVersion = '2023.0.4'
	}

	// 모든 하위 프로젝트 공통 의존성
	dependencies {
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	}
}

// Eureka Server에만 적용
configure(subprojects.findAll { it.name == 'eureka-server' }) {
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	dependencyManagement {
		imports {
			mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
		}
	}

	tasks.named('test') {
		useJUnitPlatform()
	}
}

//gateway 설정
configure(subprojects.findAll { it.name == 'gateway-service' }) {
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	dependencyManagement {
		imports {
			mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
		}
	}

	tasks.named('test') {
		useJUnitPlatform()
	}
}

// Spring Boot 서비스들에만 적용
configure(subprojects.findAll {
	it.name in ['auth-service', 'member-service', 'board-service']
}) {
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'


	dependencyManagement {
		imports {
			mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
			mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
		}
	}

	// Eureka Client 의존성 추가
	dependencies {
		implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
		implementation 'org.springframework.boot:spring-boot-starter-actuator'
	}

	tasks.named('test') {
		useJUnitPlatform()
	}
}

wrapper {
	gradleVersion = '8.4'
	distributionType = Wrapper.DistributionType.BIN
}
