plugins {
	id 'java-library'
	id 'io.spring.dependency-management' version '1.1.7'
}

dependencyManagement {
	imports {
		mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
	}
}

dependencies {
	api 'org.springframework.boot:spring-boot-starter'
	api 'org.springframework.boot:spring-boot-starter-validation'
	api 'org.springframework.boot:spring-boot-starter-actuator'

	// JWT 유틸리티
	api 'io.jsonwebtoken:jjwt-api:0.11.5'
	api 'jakarta.xml.bind:jakarta.xml.bind-api:3.0.1'
	api 'org.glassfish.jaxb:jaxb-runtime:3.0.1'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

//	// S3 공통 유틸리티
//	api 'io.awspring.cloud:spring-cloud-aws-starter-s3:3.0.3'
	// Redis 공통 설정
	api 'org.springframework.boot:spring-boot-starter-data-redis'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
